from typing import Literal

from pydantic import BaseModel, Field


class UserCreate(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    name: str | None = None
    email: str = Field(..., min_length=3)
    password: str | None = None
    date_of_birth: str | None = None


class UserLoginRequest(BaseModel):
    email: str = Field(..., min_length=3)
    password: str = Field(..., min_length=1)


class UserResponse(BaseModel):
    id: str
    name: str
    email: str
    created_at: str


class ChatRequest(BaseModel):
    prompt: str = Field(..., description="The message prompt from the user")
    history: list[dict] = Field(default_factory=list, description="A list of dictionaries containing roles and messages sent by user or ai")
    user_id: str | None = None
    chat_id: str | None = None
    title: str | None = None


class ChatResponse(BaseModel):
    response: str = Field(..., description="The final text reply generated by CLARA")
    audio: str | None = None
    user_id: str | None = None
    chat_id: str | None = None
    message_id: str | None = None


class ChatCreate(BaseModel):
    user_id: str
    title: str | None = None


class ChatSummary(BaseModel):
    id: str
    user_id: str
    title: str
    created_at: str
    updated_at: str


class MessageCreate(BaseModel):
    content: str = Field(..., min_length=1)
    role: Literal["user", "assistant"] = "user"


class MessageResponse(BaseModel):
    id: str
    chat_id: str
    role: str
    content: str
    is_liked: bool | None = None
    created_at: str


class MessageFeedbackUpdate(BaseModel):
    is_liked: bool | None = None
