from pydantic import BaseModel, Field

# --- REQUEST & RESPONSE SCHEMAS ---

class ChatRequest(BaseModel):
    prompt: str = Field(..., description="The message prompt from the user")
    history: list[dict] = Field(description='A list of dictionaries containing roles and messages sent by user or ai')
   
class ChatResponse(BaseModel):
    response: str = Field(..., description="The final text reply generated by CLARA")
    audio: str | None = None  # Holds the in-memory Base64 text string
